In [2]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[0]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
int(a[1])

1

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [7]:
points = torch.zeros(6)

points[0] = 1.0
points[1] = 2.0
points[2] = 3.0
points[3] = 4.0
points[4] = 5.0
points[5] = 6.0
points

tensor([1., 2., 3., 4., 5., 6.])

In [8]:
points = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
points

tensor([1., 2., 3., 4., 5., 6.])

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points.shape

torch.Size([3, 2])

In [11]:
points[0, 1]

tensor(1.)

In [12]:
points[0]

tensor([4., 1.])

In [13]:
points[:, 0]

tensor([4., 5., 2.])

In [14]:
points[1:, 1:]

tensor([[3.],
        [1.]])

In [15]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [16]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2156, 0.7152, 0.0722])

batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

# Mean is always 3 from end for greyscale
img_grey_naive = img_t.mean(-3)
batch_grey_naive = batch_t.mean(-3)

img_grey_naive.shape, batch_grey_naive.shape


(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [17]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
print(weights)
print(weights.shape)
print(weights.unsqueeze(-1))
print(weights.unsqueeze(-1).shape)
print(unsqueezed_weights)
print(unsqueezed_weights.shape)

tensor([0.2156, 0.7152, 0.0722])
torch.Size([3])
tensor([[0.2156],
        [0.7152],
        [0.0722]])
torch.Size([3, 1])
tensor([[[0.2156]],

        [[0.7152]],

        [[0.0722]]])
torch.Size([3, 1, 1])


In [18]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [19]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[10, 2], [31, 33]], dtype=torch.short)

short_points.dtype

torch.int16

In [21]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

double_points = torch.zeros(10, 2).to(torch.double)

In [22]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [23]:
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [26]:
a_t = a.transpose(0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-27-8575ff47c9e0>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [28]:
points_storage = points.storage()
points_storage[0]

4.0

In [29]:
points.storage()[1]

1.0

In [30]:
# Changing value in storage changes the value in the referrencing tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
# In-place operations
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [32]:
# Tensor metadata
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [33]:
second_point.size()

torch.Size([2])

In [35]:
second_point.shape

torch.Size([2])

In [36]:
points[1, 1]

tensor(3.)

In [37]:
points[1, 1].storage_offset()

3

In [38]:
points[1, 1].size()

torch.Size([])

In [39]:
points.stride()

(2, 1)

In [40]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [41]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [45]:
# Transposing
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [46]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [48]:
points.stride()

(2, 1)

In [49]:
points_t.stride()

(1, 2)

In [50]:
# Transposing in higher dimensions
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [51]:
transpose_t.shape

torch.Size([5, 4, 3])

In [52]:
print(some_t.stride())
print(transpose_t.stride())

(20, 5, 1)
(1, 5, 20)


In [3]:
# Moving tensors to the GPU
import torch

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_qpu = points.to(device='cuda')

In [5]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [6]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

with open('/content/gdrive/MyDrive/ourpoints.t', 'wb') as f:
      torch.save(points, f)

Mounted at /content/gdrive


In [11]:
with open('/content/gdrive/MyDrive/ourpoints.t', 'rb') as f:
      points = torch.load(f)

points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])